function Sthy=Sparams_hyde(X,wval)
% export the theoretical scattering coefficients with the real part on top
% and the imaginary part below
% INPUTS:
% 1) the vector X contains the input arguments in the order:
% - real(et), imag(et), real(ez), imag(ez)
% - real(mut), imag(mut), real(muz), imag(muz)
% 2) wval is the angular frequency (single value)
% % Calculation of A coefficients and scattering parameters

global m_mat n_mat a b dmat eps0 mu0 numModes includeModes q_mat solveCase...
    porttouse ket kmut num_int;

k0=sqrt(wval.^2.*eps0.*mu0); % gonna need this later
kx_1=pi/a;
ky_0=0;

Clamx = @(lamx_fx,kx_mbar_fx,kx_m_fx) (1 + exp(1j.*lamx_fx.*a)+1 + exp(-1j.*lamx_fx.*a))./...
           ((lamx_fx.^2 - kx_mbar_fx.^2).*(lamx_fx.^2-kx_m_fx.^2));
Clamy = @(lamy_fx,ky_nbar_fx,ky_n_fx) (exp(1j.*lamy_fx.*b)-1 + exp(-1j.*lamy_fx.*b)-1)./...
           ((lamy_fx.^2 - ky_nbar_fx.^2).*(lamy_fx.^2 - ky_n_fx.^2));
       
% % how to preallocate?
Sthy=[];
% A11=zeros(numModes,numModes);
% A12=A11;
% Bmat=zeros(2*numModes,1);
A11=zeros(numModes,numModes);
A12=A11;
A13=A11;
A14=A11;
A21=A11;
A22=A11;
A23=A11;
A24=A11;
B1=zeros(numModes,1);
B2=B1;
B3=B1;
B4=B1;

% cases:
%  1 - isotropic, dielectric, non-magnetic (et=ez=er) & (mut=muz=mu0)
%  2 - isotropic, non-dielectric, magnetic (et=ez=eps0) & (mut=muz=mur)
%  3 - isotropic, dielectric, magnetic (et=ez=er) & (mut=muz=mur)
%  4 - uniaxial, dielectric, non-magnetic (et,ez) & (mut=muz=mu0)
%  5 - uniaxial, non-dielectric, magnetic (et=ez=eps0) & (mut,muz)
%  6 - uniaxial, dielectric, magnetic (et,ez) & (mut,muz) 
switch solveCase
    case 1
        ret=X(1);
        iet=X(2);
        rez=ret;
        iez=iet;
        rmut=1;
        imut=0;
        rmuz=rmut;
        imuz=imut;
    
    case  2 
        ret=1;
        iet=0;
        rez=ret;
        iez=iet;
        rmut=X(1);
        imut=X(2);
        rmuz=rmut;
        imuz=imut;
    
    case 3
        ret=X(1);
        iet=X(2);
        rez=ret;
        iez=iet;
        rmut=X(3);
        imut=X(4);
        rmuz=rmut;
        imuz=imut;
    
    case 4
        ret=X(1);
        iet=X(2);
        rez=X(3);
        iez=X(4);
        rmut=1;
        imut=0;
        rmuz=rmut;
        imuz=imut;
        
    case 5
        ret=1;
        iet=0;
        rez=ret;
        iez=iet;
        rmut=X(1);
        imut=X(2);
        rmuz=X(3);
        imuz=X(4);
    case 6 
        ret=X(1);
        iet=X(2);
        rez=X(3);
        iez=X(4);
        rmut=X(5);
        imut=X(6);
        rmuz=X(7);
        imuz=X(8);
    case 7
        ret=real(ket);
        iet=imag(ket);
        rez=X(1);
        iez=X(2);
        rmut=real(kmut);
        imut=imag(kmut);
        rmuz=X(3);
        imuz=X(4);
end

% put the real and imaginary parts together
et=ret+1j*iet;
ez=rez+1j*iez;
mut=rmut+1j*imut;
muz=rmuz+1j*imuz;

et=et.*eps0;
ez=ez.*eps0;
mut=mut.*mu0;
muz=muz.*mu0;

% % display some useful info
% display(['Current Values are:'])
% display(['widx = ' num2str(wvalidx)])
% display(['et = ' num2str(et)]) 
% display(['ez = ' num2str(ez)])
% display(['mut = ' num2str(mut)])
% display(['muz = ' num2str(muz)])

for didx=1:length(dmat) % if we have two thicknesses
    d=dmat(didx);  
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   qbar_idx=1;
   for qbar=q_mat % TE_mn/TM_mn index       
       mbar=m_mat(qbar);
       nbar=n_mat(qbar);
       kx_mbar=mbar.*pi/a;
       ky_nbar=nbar.*pi/b;
       q_idx=1;
       for q=q_mat
           m=m_mat(q);
           n=n_mat(q);
           kx_m=m*pi/a;
           ky_n=n*pi/b;
           kc_mn=sqrt(kx_m.^2 + ky_n.^2);
           gamma_mn=sqrt(kc_mn.^2 - k0.^2);
           gamma_10=sqrt(kx_1.^2 - k0.^2);
           Z_te_mn=1j.*wval.*mu0/gamma_mn;
           Z_te_10=1j.*wval.*mu0/gamma_10;
           Z_tm_mn=gamma_mn./(1j.*wval.*eps0);
           
         % the A coefficients
           A11(qbar_idx,q_idx) = ( ((-kx_m.*a.*b)./(4.*Z_te_mn)).*(1+1.*(n==0)).*(q==qbar) )...
               +(...
                ( (1j.*kx_mbar)./(4.*pi.^2) ).*...
                (...
                  4.*quad2d(@(lamx,lamy) -kx_m.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                + 4.*quad2d(@(lamx,lamy) -kx_m.*kx_m.*lamy.^4.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 )...
                ) ...
                -(...    
                  ((1j.*kx_mbar)./(4.*pi.^2)).*...
                   (...
                     4.*quad2d(@(lamx,lamy) ky_n.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                   - 4.*quad2d(@(lamx,lamy) ky_n.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...  
                   )...
                );
            
           A12(qbar_idx,q_idx)=( ((ky_n.*a.*b)./(4.*Z_tm_mn)).*(q==qbar) ) ...
                +(...
                 ( (1j.*kx_mbar)./(4.*pi.^2) ).*...
                  (...
                   4.*quad2d(@(lamx,lamy) ky_n.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 + 4.*quad2d(@(lamx,lamy) ky_n.*kx_m.*lamy.^4.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                  )...
                 )...
                -(...    
                 ((1j.*kx_mbar)./(4.*pi.^2)).*...
                 (...
                   4.*quad2d(@(lamx,lamy) kx_m.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 - 4.*quad2d(@(lamx,lamy) kx_m.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...  
                 )...
                );       
            
           A13(qbar_idx,q_idx)=(...
                 ( (1j.*kx_mbar)./(4.*pi.^2) ).*...
                  (...
                  4.*quad2d(@(lamx,lamy) kx_m.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                + 4.*quad2d(@(lamx,lamy) kx_m.*kx_m.*lamy.^4.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                   )...
                 )...
                +(...    
                 ((1j.*kx_mbar)./(4.*pi.^2)).*...
                 (...
                   4.*quad2d(@(lamx,lamy) ky_n.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 - 4.*quad2d(@(lamx,lamy) ky_n.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...  
                 )...
                );
            
           A14(qbar_idx,q_idx)=(...
                 ( (1j.*kx_mbar)./(4.*pi.^2) ).*...
                  (...
                  4.*quad2d(@(lamx,lamy) -ky_n.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                + 4.*quad2d(@(lamx,lamy) -ky_n.*kx_m.*lamy.^4.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                   )...
                 )...
                +(...    
                 ((1j.*kx_mbar)./(4.*pi.^2)).*...
                 (...
                   4.*quad2d(@(lamx,lamy) kx_m.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 - 4.*quad2d(@(lamx,lamy) kx_m.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...  
                 )...
                );
            
            A21(qbar_idx,q_idx) =( ((ky_n.*a.*b)./(4.*Z_te_mn)).*(q==qbar) )...
               +(...
                ( (1j.*ky_nbar)./(4.*pi.^2) ).*...
                (...
                  4.*quad2d(@(lamx,lamy) kx_m.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                - 4.*quad2d(@(lamx,lamy) kx_m.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 )...
                ) ...
                +(...    
                  ((1j.*ky_nbar)./(4.*pi.^2)).*...
                   (...
                     4.*quad2d(@(lamx,lamy) ky_n.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                   + 4.*quad2d(@(lamx,lamy) ky_n.*ky_n.*lamx.^4.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...  
                   )...
                );
            
           A22(qbar_idx,q_idx)=( ((kx_m.*a.*b)./(4.*Z_tm_mn)).*(q==qbar).*(n~=0) ) ...
                -(...
                 ( (1j.*ky_nbar)./(4.*pi.^2) ).*...
                  (...
                   4.*quad2d(@(lamx,lamy) ky_n.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 - 4.*quad2d(@(lamx,lamy) ky_n.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                  )...
                 )...
                +(...    
                 ((1j.*ky_nbar)./(4.*pi.^2)).*...
                 (...
                   4.*quad2d(@(lamx,lamy) kx_m.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 + 4.*quad2d(@(lamx,lamy) kx_m.*ky_n.*lamx.^4.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...  
                 )...
                ); 
            
            A23(qbar_idx,q_idx)=(...
                 ( (1j.*ky_nbar)./(4.*pi.^2) ).*...
                  (...
                  4.*quad2d(@(lamx,lamy) -kx_m.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                - 4.*quad2d(@(lamx,lamy) -kx_m.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                   )...
                 )...
                -(...    
                 ((1j.*ky_nbar)./(4.*pi.^2)).*...
                 (...
                   4.*quad2d(@(lamx,lamy) ky_n.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 + 4.*quad2d(@(lamx,lamy) ky_n.*ky_n.*lamx.^4.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...  
                 )...
                );
            
            A24(qbar_idx,q_idx)=(...
                 ( (1j.*ky_nbar)./(4.*pi.^2) ).*...
                  (...
                  4.*quad2d(@(lamx,lamy) ky_n.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                - 4.*quad2d(@(lamx,lamy) ky_n.*kx_m.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                   )...
                 )...
                -(...    
                 ((1j.*ky_nbar)./(4.*pi.^2)).*...
                 (...
                   4.*quad2d(@(lamx,lamy) kx_m.*ky_n.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
                 + 4.*quad2d(@(lamx,lamy) kx_m.*ky_n.*lamx.^4.*Clamx(lamx,kx_mbar,kx_m).*Clamy(lamy,ky_nbar,ky_n).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...  
                 )...
                );

            q_idx=q_idx+1;
       end % end q
     
     % the B coefficients 
       B1(qbar_idx,1) =((-kx_1.*a.*b.*(qbar==1))./(2.*Z_te_10))...
           +(...
             ( (1j.*kx_mbar)./(4.*pi.^2) ).*...
              (...
                4.*quad2d(@(lamx,lamy) kx_1.*kx_1.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_1).*Clamy(lamy,ky_nbar,ky_0).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
              + 4.*quad2d(@(lamx,lamy) kx_1.*kx_1.*lamy.^4.*Clamx(lamx,kx_mbar,kx_1).*Clamy(lamy,ky_nbar,ky_0).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
               )...
             );
       B2(qbar_idx,1)=(...
             ( (-1j.*ky_nbar)./(4.*pi.^2) ).*...
              (...
                4.*quad2d(@(lamx,lamy) kx_1.*kx_1.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_1).*Clamy(lamy,ky_nbar,ky_0).*gfpi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
              - 4.*quad2d(@(lamx,lamy) kx_1.*kx_1.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_1).*Clamy(lamy,ky_nbar,ky_0).*gfphi_00_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
               )...
                        );
       B3(qbar_idx,1) =(...
             ( (1j.*kx_mbar)./(4.*pi.^2) ).*...
              (...
                4.*quad2d(@(lamx,lamy) kx_1.*kx_1.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_1).*Clamy(lamy,ky_nbar,ky_0).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
              + 4.*quad2d(@(lamx,lamy) kx_1.*kx_1.*lamy.^4.*Clamx(lamx,kx_mbar,kx_1).*Clamy(lamy,ky_nbar,ky_0).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
               )...
                     );
       B4(qbar_idx,1)=(...
             ( (-1j.*ky_nbar)./(4.*pi.^2) ).*...
              (...
                4.*quad2d(@(lamx,lamy) kx_1.*kx_1.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_1).*Clamy(lamy,ky_nbar,ky_0).*gfpi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
              - 4.*quad2d(@(lamx,lamy) kx_1.*kx_1.*lamx.^2.*lamy.^2.*Clamx(lamx,kx_mbar,kx_1).*Clamy(lamy,ky_nbar,ky_0).*gfphi_0d_mt(wval,d,et,ez,mut,muz,lamx,lamy),0,50e3,0,50e3,'abstol',1e-10,'reltol',1e-10)...
               )...
                        );
                    
       qbar_idx=qbar_idx+1;
   end % end qbar 
   
  % put the A matrix together 
   A1=[A11 A12; A21 A22];
   A2=[A13 A14; A23 A24];
   A3=-A2;
   A4=-A1;
   Amat=[A1 A2; A3 A4];
   Bmat=[B1; B2; B3; B4];
%    Cmat=Amat\Bmat;
   Cmat=pinv(Amat)*Bmat;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  % scattering parameters
    S11thy=Cmat(1);
    tidx=(length(Cmat)/2)+1;
    S21thy=Cmat(tidx);
    S22thy=S11thy;
    S12thy=S21thy;
    if porttouse==1
        Sthy=cat(1,Sthy,real(S11thy),imag(S11thy),real(S21thy),imag(S21thy)); % real, then imag of each S parameter
    elseif porttouse==2
        Sthy=cat(1,Sthy,real(S12thy),imag(S12thy),real(S22thy),imag(S22thy)); % real, then imag of each S parameter
    else % use all 4
        Sthy=cat(1,Sthy,real(S11thy),imag(S11thy),real(S21thy),imag(S21thy),real(S12thy),imag(S12thy),...
          real(S22thy),imag(S22thy)); % real, then imag of each S parameter
    end
end % end of dmat loop


end % end of function

    